services:
  # 1. OLLAMA SERVICE (Backend Model Server)
  ollama:
    image: ollama/ollama:latest
    container_name: rag_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama 
    networks:
      - rag_net
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # 2. FASTAPI SERVICE
  fastapi_app:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434 
    depends_on:
      - ollama
    volumes:
      - ./data/docs:/app/data/docs        # PDF folder sync
      - ./chroma_db_local:/app/chroma_db_local  # DB sync
    networks:
      - rag_net
    restart: always

# Shared Storage & Network Definition
volumes:
  ollama_storage:

networks:
  rag_net:
    driver: bridge